title: Observatório Oceanográfico
name: Observatório Oceanográfico
email: observatoriooceanografico@gmail.com
description: >-
  Laboratório institucional vinculado à Universidade Federal Fluminense.
url: "https://observatorio-oceanografico.github.io"
baseurl: ""
repository: observatorio-oceanografico/observatorio-oceanografico.github.io

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

logo: "/assets/img/O2_logo_branco.png"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

navigation: main

collections:
  teaching:
    output: true
    permalink: /teaching/:path/
  projects:
    output: true
    permalink: /projects/:path/
  extensao:
    output: true
    permalink: /extensao/:path/
  equipe:
    output: true
    permalink: /equipe/:path/
